  owner: PrePressOS
  repo: status

  sites:
    - name: PrePressOS App
      url: https://prepressos.com/health
      expectedStatusCodes:
        - 200
    - name: PrePressOS Landing
      url: https://prepressos.com

  status-website:
    cname: status.prepressos.com
    name: PrePressOS Status
    introTitle: "PrePressOS is operational."
    introMessage: Real-time uptime monitoring for prepressos.com.
    navbar:
      - title: Status
        href: /
      - title: PrePressOS
        href: https://prepressos.com
